### ISSUE TITLE
app error

### ISSUE THREAD

**Issue by AttemptD** [moifort/swiftUI-photo-library-picker#2]
when sheet show me .The app was error 

the xcode show me : "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
Fatal error: Attempted to read an unowned reference but the object was already deallocated

**Comment by moifort** [comment]
Do you have more information, code? How you implement it?

**Comment by ryaaanb** [comment]
I had the same problem. A fix was changing the unowned to a weak.

`checkStatus { [unowned self]` -> `checkStatus { [weak self]`.

**Comment by moifort** [comment]
Thanks @ryaaanb! @AttemptD can you confirm that your issue is fixed with the answer of @ryaaanb ?

**Comment by AttemptD** [comment]
I already fixed it thank you @ryaaanb @moifort

**Comment by vulamobile** [comment]
Thanks for this. 

> I had the same problem. A fix was changing the unowned to a weak.
> `checkStatus { [unowned self]` -> `checkStatus { [weak self]`.

Solved the issue for me
